#!/usr/bin/ruby
# coding: utf-8
#
# Ruby IRC bot
#
# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://sam.zoy.org/wtfpl/COPYING for more details. 

# add locla library directory to $LOAD_PATH
$: << File.expand_path("../lib", __FILE__)

require 'optparse'
require 'rib/rib'

# initialize configuration from file
config = RIB::Configuration.new( "config" )

# handle possible arguments
OptionParser.new do |opts|
  opts.banner = "Usage: #{File.basename($0)} [options]"

  opts.on("-i", "--irc [HOSTNAME]", "IRC Server to connect to") do |irc|
    config.irc(irc)
  end
  opts.on("-n", "--nick [NICKNAME]", "nickname for the bot") do |n|
    config.nick(n)
  end
  opts.on("-c", "--channel [CHANNEL]", String, "which channel to join") do |c|
    c = c.gsub(/\A([^\#].*)/, '#\0')
    config.channel(c)
  end
  opts.on("-f", "--file [CONFFILE]", "read configuration from this file") do |f|
    config.update(f)
  end
  opts.on("-v", "--verbose", "write to STDOUT instead of logfile") do |f|
    config.verbose = true
  end
  # No argument, shows at tail.  This will print an options summary.
  opts.on_tail("-h", "--help", "show this message") do
    puts opts
    exit
  end
end.parse!

aibot = RIB::Bot.new( config )

aibot.run
