#!/usr/bin/ruby
# coding: utf-8

# Just copy this file over in the root dir and execute it directly or
# with 'ruby rib-irc'.

# add local library directory to $LOAD_PATH if not used with bundler
# or gem
# $LOAD_PATH << File.expand_path('../lib', __FILE__)

require 'rib'

rib = RIB::Bot.new(:irc) do |bot|
  bot.connection.server = 'irc.quakenet.org'
  bot.connection.port = 6667
  bot.connection.channels = ['#rib']
  bot.qmsg = 'See you later, shitlords!'
  bot.debug = false
  bot.admin = 'ribmaster'
end

rib.run

