#!/usr/bin/ruby
# coding: utf-8

# Just copy this file over in the root dir and execute it directly or
# with 'ruby rib-xmpp'.

# add local library directory to $LOAD_PATH if not used with bundler
# or gem
# $LOAD_PATH << File.expand_path('../lib', __FILE__)

require 'rib'

rib = RIB::Bot.new(:xmpp) do |bot|
  bot.connection.server = 'muc.xmpp.example.com'
  bot.connection.muc = 'bottest'
  bot.connection.jid = 'rib@xmpp.example.com'
  bot.connection.password = 'aBcDeFgHiJkLmNoPqRsTuVwXyZ'
  bot.qmsg = 'See you later, shitlords!'
  bot.debug = false
  bot.admin = 'ribmaster'
end

rib.run

